version: '3.4'

services:
  mongo:
    image: mongo
    container_name: sport-mongo
    restart: always
    ports:
      - 27020:27017
    volumes:
      - ./database/data:/data/db
      # - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    # MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_UNAME}
    # MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASW}
    # MONGO_USERNAME: ${MONGO_USER}
    # MONGO_PASSWORD: ${MONGO_PASW}

  sportbot:
    image: sportbot
    container_name: sport-bot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PROD_MONGODB_URL: mongodb://mongo:27017/${DB_NAME}
    links:
      - mongo
